config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  root "users#new"

  resources :users, only: [:new, :create]
  resources :short_url_generators, only: [:new, :create]
  get "/login", to: "users#login"
  post "/login", to: "users#login"
  namespace :api do
    namespace :v1 do
      resources :users, only: [:create] do
        collection do
          post :login
        end
      end
      resources :short_url_generators, only: [:create]
    end
  end
  get "/:short_url", to: "api/v1/short_url_generators#short_url"
end

app/controllers/api/v1/short_url_generators_controller.rb
class Api::V1::ShortUrlGeneratorsController < ApplicationController
  before_action :authenticate_user, only: [:create]

  def create
    short_url_data = ShortUrlGeneratorService.new(short_url_params.merge(user:current_user)).call
    short_code = short_url_data[:short_url]
    short_url_data[:short_url] = "#{request.base_url}/#{short_code}"
    if short_url_data.save
      render_success_response(data: { short_url: short_url_data.short_url}, message: "Short url created successfully", status:200)
    else
      render_error_response(error: short_url_data.errors.full_messages, message: "Short url creation failed", status:422)
    end    
  end

  def short_url

    short_url = "#{request.base_url}/#{params[:short_url]}"
    short_url_data = ShortUrl.find_by(short_url:short_url)
    if short_url_data
      redirect_to short_url_data.original_url, allow_other_host: true, status:302
    else
      render json: { error: "Short url not found", message: "Short url not found" }, status:422
    end
  end

  private

  def short_url_params
    params.require(:short_url).permit(ShortUrl::PERMITTED_ATTRIBUTES)
  end
end

app/controllers/short_url_generators_controller.rb
class ShortUrlGeneratorsController < ApplicationController
    before_action :authenticate_user
  
    def new
      @short_url = ShortUrl.new
    end  
  
    def create
      @short_url_data = ShortUrlGeneratorService.new(short_url_params.merge(user:current_user)).call
      short_code = @short_url_data[:short_url]
      @short_url_data[:short_url] = "#{request.base_url}/#{short_code}"
      if @short_url_data.save
        flash.now[:notice] = "Shortened URL created successfully! You can use it now."
        render :show
      else
        flash.now[:alert] = @short_url_data.errors.full_messages.join(", ")
        render :new, status: :unprocessable_entity
      end
    end
  
    private
  
    def short_url_params
      params.require(:short_url).permit(ShortUrl::PERMITTED_ATTRIBUTES)
    end
  end
  

app/helpers/api/v1/short_url_generators_helper.rb
module Api::V1::ShortUrlGeneratorsHelper
end

app/helpers/short_url_generators_helper.rb
module ShortUrlGeneratorsHelper
end

app/views/short_url_generators/_form.html.erb
<%= form_with(model: ShortUrl.new, url: short_url_generators_path, method: :post, html: { class: "url-form" }) do |f| %>
    <div class="form-group">
      <%= f.label :original_url %>
      <%= f.text_field :original_url, class: "form-control" %>
    </div>
  
    <%= f.submit "Shorten URL", class: "btn btn-primary" %>
  <% end %>
  

app/views/short_url_generators/new.html.erb
<div class="url-shortener-container">
  <h2 class="text-center">URL Shortener</h2>
  <%= render 'form' %>
</div>

app/views/short_url_generators/show.html.erb
<div class="url-shortener-container">
  <h2>Your Shortened URL</h2>
  <p><strong>Original URL:</strong> <%= @short_url_data.original_url %></p>
  <p><strong>Shortened URL:</strong> <a href="<%= @short_url_data.short_url %>" target="_blank"><%= @short_url_data.short_url %></a></p>

  <%= link_to "Create Another", new_short_url_generator_path, class: "btn btn-primary" %>
</div>